version: '3'
services:
  d_web:
    build:
      context: .
      dockerfile: ./docker_conf/dev_python/Dockerfile
    volumes:
      - .:/code
    env_file: 
      - .env
    ports:
      - "22:22"
    depends_on:
      - d_selenium
    links:
      - d_selenium:selenium
  d_selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - "5901:5900"
    shm_size: 128M
